version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=healthwave_db
      - MYSQL_USER=losthumanity
      - MYSQL_PASSWORD=healthWave123!
      - MYSQL_ROOT_PASSWORD=RoothealthWave123!
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local